/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { MaterialNode } from "three/examples/jsm/nodes/Nodes.js";

export default function Lotus() {
  const { nodes, materials } = useGLTF("/lotus.glb");
  return (
    <group scale={0.5} position={[0,0,-1]} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube.geometry}
        material={nodes.Cube.material}
        position={[2.609, 1.143, 0.029]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube001.geometry}
        material={nodes.Cube001.material}
        position={[2.369, 1.143, -1.183]}
        rotation={[0, 0.296, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube002.geometry}
        material={nodes.Cube002.material}
        position={[0.285, 1.143, -2.678]}
        rotation={[0, 1.316, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube003.geometry}
        material={nodes.Cube003.material}
        position={[1.443, 1.143, -2.249]}
        rotation={[0, 0.796, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube004.geometry}
        material={nodes.Cube004.material}
        position={[0.726, 1.143, 2.03]}
        rotation={[0, -1.528, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube005.geometry}
        material={nodes.Cube005.material}
        position={[2.118, 1.143, 1.657]}
        rotation={[0, -0.736, 0]}
        scale={[1.082, 1, 1.116]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube006.geometry}
        material={nodes.Cube006.material}
        position={[-0.685, 1.143, 1.977]}
        rotation={[Math.PI, -1.114, Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube007.geometry}
        material={nodes.Cube007.material}
        position={[-1.733, 1.143, 1.324]}
        rotation={[Math.PI, -0.818, Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube008.geometry}
        material={nodes.Cube008.material}
        position={[-1.097, 1.143, -2.86]}
        rotation={[-Math.PI, 1.228, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube009.geometry}
        material={nodes.Cube009.material}
        position={[-2.24, 1.143, -2.223]}
        rotation={[-Math.PI, 0.742, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube010.geometry}
        material={nodes.Cube010.material}
        position={[-2.468, 1.143, 0.331]}
        rotation={[Math.PI, -0.278, Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube011.geometry}
        material={nodes.Cube011.material}
        position={[-2.688, 1.143, -0.885]}
        rotation={[-Math.PI, 0.242, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube012.geometry}
        material={nodes.Cube012.material}
        position={[-0.308, 1.365, 1.637]}
        rotation={[Math.PI, -1.365, Math.PI]}
        scale={[0.581, 0.821, 0.809]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube013.geometry}
        material={nodes.Cube013.material}
        position={[0.685, 1.365, 1.477]}
        rotation={[0, -1.257, 0]}
        scale={[0.586, 0.821, 0.805]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube014.geometry}
        material={nodes.Cube014.material}
        position={[-1.249, 1.365, 0.971]}
        rotation={[3.042, -0.657, 3.073]}
        scale={[0.693, 0.821, 0.715]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube015.geometry}
        material={nodes.Cube015.material}
        position={[-1.962, 1.365, 0.8]}
        rotation={[Math.PI, -0.379, Math.PI]}
        scale={[0.796, 0.821, 0.598]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube016.geometry}
        material={nodes.Cube016.material}
        position={[1.486, 1.365, 1.035]}
        rotation={[0, -0.717, 0]}
        scale={[0.712, 0.821, 0.696]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube017.geometry}
        material={nodes.Cube017.material}
        position={[2, 1.365, 0.426]}
        rotation={[0, -0.421, 0]}
        scale={[0.778, 0.821, 0.622]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube018.geometry}
        material={nodes.Cube018.material}
        position={[1.531, 1.365, -1.034]}
        rotation={[0, 0.871, 0]}
        scale={[0.748, 0.821, 0.8]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube019.geometry}
        material={nodes.Cube019.material}
        position={[2.015, 1.365, -0.37]}
        rotation={[0, 0.079, 0]}
        scale={[0.821, 0.821, 0.563]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube020.geometry}
        material={nodes.Cube020.material}
        position={[-1.512, 1.365, -0.647]}
        rotation={[-Math.PI, 0.739, -Math.PI]}
        scale={[0.707, 0.821, 0.701]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube021.geometry}
        material={nodes.Cube021.material}
        position={[-1.84, 1.365, 0.018]}
        rotation={[-Math.PI, 0.219, -Math.PI]}
        scale={[0.808, 0.821, 0.583]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube022.geometry}
        material={nodes.Cube022.material}
        position={[-0.656, 1.365, -1.199]}
        rotation={[-Math.PI, 1.239, -Math.PI]}
        scale={[0.589, 0.821, 0.803]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube023.geometry}
        material={nodes.Cube023.material}
        position={[0.334, 1.365, -1.37]}
        rotation={[-Math.PI, 1.535, -Math.PI]}
        scale={[0.563, 0.821, 0.821]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder.geometry}
        material={nodes.Cylinder.material}
        position={[0.162, 0.647, 0.097]}
        scale={[1, 0.547, 1]}
      />
    </group>
  );
}

useGLTF.preload("/lotus.glb");

